// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ridemetrx/features/auth/domain/models/user.dart';
import 'package:ridemetrx/features/bikes/domain/models/bike.dart';
import 'package:ridemetrx/features/bikes/domain/models/component_setting.dart';
import 'package:ridemetrx/features/bikes/domain/models/fork.dart';
import 'package:ridemetrx/features/bikes/domain/models/setting.dart';
import 'package:ridemetrx/features/bikes/domain/models/shock.dart';
import 'package:ridemetrx/features/community/domain/models/community_setting.dart';
import 'package:ridemetrx/features/community/domain/models/location_data.dart';
import 'package:ridemetrx/features/sync/domain/models/data_conflict.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(BikeAdapter());
    registerAdapter(CommunitySettingAdapter());
    registerAdapter(ComponentAdapter());
    registerAdapter(DataConflictAdapter());
    registerAdapter(ForkAdapter());
    registerAdapter(LocationDataAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(ShockAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(BikeAdapter());
    registerAdapter(CommunitySettingAdapter());
    registerAdapter(ComponentAdapter());
    registerAdapter(DataConflictAdapter());
    registerAdapter(ForkAdapter());
    registerAdapter(LocationDataAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(ShockAdapter());
  }
}
