// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:suspension_pro/features/auth/domain/models/user.dart';
import 'package:suspension_pro/features/bikes/domain/models/bike.dart';
import 'package:suspension_pro/features/bikes/domain/models/component_setting.dart';
import 'package:suspension_pro/features/bikes/domain/models/fork.dart';
import 'package:suspension_pro/features/bikes/domain/models/setting.dart';
import 'package:suspension_pro/features/bikes/domain/models/shock.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(BikeAdapter());
    registerAdapter(ComponentAdapter());
    registerAdapter(ForkAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(ShockAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(BikeAdapter());
    registerAdapter(ComponentAdapter());
    registerAdapter(ForkAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(ShockAdapter());
  }
}
